#Load Dataset

In [1]:
import pandas as pd
import numpy as np

#Creating DataFrame

In [3]:
#Create from List

first = [1,2,3,4,5,6]
second = [2,3,4,5,6,7]
df1 = pd.DataFrame(list(zip(first, second)), columns=['first', 'second'])

print(df1)
display(df1)

   first  second
0      1       2
1      2       3
2      3       4
3      4       5
4      5       6
5      6       7

   first  second
0      1       2
1      2       3
2      3       4
3      4       5
4      5       6
5      6       7

In [11]:
#Create from Array

array= np.array ([[1,2,3], [4,5,6], [7,8,9]])
df2 = pd.DataFrame(array, columns=['first', 'second', 'third'])

df2

   first  second  third
0      1       2      3
1      4       5      6
2      7       8      9

In [15]:
#Create from Series

first = pd.Series([1,2,3,4,5,6])
second = pd.Series([2,3,4,5,6,7])
df3= pd.DataFrame(first, columns=['first'])
df3['second']= second

df3

   first  second
0      1       2
1      2       3
2      3       4
3      4       5
4      5       6
5      6       7

In [ ]:
#Create from Tuple

In [ ]:
#Creat from Dict

In [ ]:
#Connecting Data from Drive